export const data2 = [
  {
    key: 1,
    componentName: "Blog",
    componentCount: "6",
    uiName: "Marketing UI",
    path: "./image/blog.webp",
  },
  {
    key: 2,
    componentName: "CTA",
    componentCount: "6",
    uiName: "Marketing UI",
    path: "./image/cta.webp",
  },
  {
    key: 3,
    componentName: "Contact",
    componentCount: "13",
    uiName: "Marketing UI",
    path: "./image/contact.webp",
  },
  {
    key: 4,
    componentName: "Email Templates",
    componentCount: "7",
    uiName: "Marketing UI",
    path: "./image/email-templates.webp",
  },
  {
    key: 5,
    componentName: "FAQ",
    componentCount: "5",
    uiName: "Marketing UI",
    path: "./image/faq.webp",
  },
  {
    key: 6,
    componentName: "Footers",
    componentCount: "10",
    uiName: "Marketing UI",
    path: "./image/footers.webp",
  },
  {
    key: 7,
    componentName: "Portfolio",
    componentCount: "5",
    uiName: "Marketing UI",
    path: "./image/portfolio.webp",
  },
  {
    key: 8,
    componentName: "Pricing",
    componentCount: "7",
    uiName: "Marketing UI",
    path: "./image/pricing.webp",
  },
  {
    key: 9,
    componentName: "Heros",
    componentCount: "11",
    uiName: "Marketing UI",
    path: "./image/heros.webp",
  },
];