export const data = [
  {
    key: 1,
    componentName: "Alerts",
    componentCount: "9 components",
    uiName: "Application UI",
    path: "./image/alerts.webp",
  },
  {
    key: 2,
    componentName: "Avatars",
    componentCount: "10 components",
    uiName: "Application UI",
    path: "./image/avatars.webp",
  },
  {
    key: 3,
    componentName: "Breadcrumbs",
    componentCount: "5 components",
    uiName: "Application UI",
    path: "./image/breadcrumbs.webp",
  },

  {
    key: 4,
    componentName: "Buttons",
    componentCount: "10 components",
    uiName: "Application UI",
    path: "./image/buttons.webp",
  },
  {
    key: 5,
    componentName: "Cards",
    componentCount: "9 components",
    uiName: "Application UI",
    path: "./image/cards.webp",
  },
  {
    key: 6,
    componentName: "Cookies",
    componentCount: "6 components",
    uiName: "Application UI",
    path: "./image/cookies.webp",
  },
  {
    key: 7,
    componentName: "Dropdowns",
    componentCount: "6 components",
    uiName: "Application UI",
    path: "./image/dropdowns.webp",
  },
  {
    key: 8,
    componentName: "Forms",
    componentCount: "4 components",
    uiName: "Application UI",
    path: "./image/forms.webp",
  },
  {
    key: 9,
    componentName: "Inputs",
    componentCount: "13 components",
    uiName: "Application UI",
    path: "./image/inputs.webp",
  },
  {
    key: 10,
    componentName: "Modals",
    componentCount: "5 components",
    uiName: "Application UI",
    path: "./image/modals.webp",
  },
  {
    key: 11,
    componentName: "Navbars",
    componentCount: "6 components",
    uiName: "Application UI",
    path: "./image/navbars.webp",
  },
];