export const data = [
  {
    key: 1,
    componentName: "Alerts",
    componentCount: "9 components",
    uiName: "Application UI",
    path: "./image/alerts.webp",
    link: "/categories/alerts", // Dynamic category path
  },
  {
    key: 2,
    componentName: "Avatars",
    componentCount: "10 components",
    uiName: "Application UI",
    path: "./image/avatars.webp",
    link: "/categories/avatars",
  },
  {
    key: 3,
    componentName: "Breadcrumbs",
    componentCount: "5 components",
    uiName: "Application UI",
    path: "./image/breadcrumbs.webp",
    link: "/categories/breadcrumbs",
  },
  {
    key: 4,
    componentName: "Buttons",
    componentCount: "10 components",
    uiName: "Application UI",
    path: "./image/buttons.webp",
    link: "/categories/buttons",
  },
  {
    key: 5,
    componentName: "Cards",
    componentCount: "9 components",
    uiName: "Application UI",
    path: "./image/cards.webp",
    link: "/categories/cards",
  },
  {
    key: 6,
    componentName: "Cookies",
    componentCount: "6 components",
    uiName: "Application UI",
    path: "./image/cookies.webp",
    link: "/categories/cookies",
  },
  {
    key: 7,
    componentName: "Dropdowns",
    componentCount: "6 components",
    uiName: "Application UI",
    path: "./image/dropdowns.webp",
    link: "/categories/dropdowns",
  },
  {
    key: 8,
    componentName: "Forms",
    componentCount: "4 components",
    uiName: "Application UI",
    path: "./image/forms.webp",
    link: "/categories/forms",
  },
  {
    key: 9,
    componentName: "Inputs",
    componentCount: "13 components",
    uiName: "Application UI",
    path: "./image/inputs.webp",
    link: "/categories/inputs",
  },
  {
    key: 10,
    componentName: "Modals",
    componentCount: "5 components",
    uiName: "Application UI",
    path: "./image/modals.webp",
    link: "/categories/modals",
  },
  {
    key: 11,
    componentName: "Navbars",
    componentCount: "6 components",
    uiName: "Application UI",
    path: "./image/navbars.webp",
    link: "/categories/navbars",
  },
  {
    key: 12,
    componentName: "Auth Form",
    componentCount: "9 components",
    uiName: "Application UI",
    path: "./image/sign-in-and-registration.webp",
    link: "/categories/authform",
  },
  {
    key: 13,
    componentName: "Skeleton",
    componentCount: "8 components",
    uiName: "Application UI",
    path: "./image/skeleton.webp",
    link: "/categories/skeleton",
  },
  {
    key: 14,
    componentName: "Tables",
    componentCount: "6 components",
    uiName: "Application UI",
    path: "./image/tables.webp",
    link: "/categories/tables",
  },
  {
    key: 15,
    componentName: "Tabs",
    componentCount: "4 components",
    uiName: "Application UI",
    path: "./image/tabs.webp",
    link: "/categories/tabs",
  },
  {
    key: 16,
    componentName: "Tooltip",
    componentCount: "7 components",
    uiName: "Application UI",
    path: "./image/tooltip.webp",
    link: "/categories/tooltip",
  }
];
